import requests
from typing import List
import json

headers = {
    "authority": "airportcodes.io",
    "accept": "*/*",
    "accept-language": "en-GB,en-US;q=0.9,en;q=0.8",
    "cookie": "_ga=GA1.1.1776268612.1665360952; cookie_consent=%7B%22preferences%22%3Afalse%2C%22statistics%22%3Afalse%2C%22marketing%22%3Afalse%7D; FCCDCF=%5Bnull%2Cnull%2Cnull%2C%5B%22CPgocUAPgocUAEsABBENCkCgAAAAAH_AABpYAAAOhQD2F2K2kKEkfjSUWYAQBCujIEIhUAAAAECBIAAAAUgQAgFIIAgAAlACAAAAABAQAQCAgAQABAAAoACgAAAAAAAAAAAAAAQQAABAAIAAAAAAAAEAQAAIAAQAAAAAAABEhCAAQQAEAAAAAAAAAAAAAAAAAAABAAA%22%2C%221~%22%2C%228007520D-03DB-4FDD-B772-7BF2CD10B46E%22%5D%2Cnull%2Cnull%2C%5B%5D%5D; _ga_YTMNFT84BW=GS1.1.1665360952.1.1.1665361540.0.0.0",
    "referer": "https://airportcodes.io/en/all-airports/?filters[country]=FR",
    "sec-ch-ua": '"Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"macOS"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
}

COLUMNS = [
    # "airport.icao",
    "airport.iata",
    # "airport.link_name",
    "airport.type",
    "city.name",
    "country.name",
]

PAGE_SIZE = 1000
LARGE_AIRPORT = "large_airport"

eligible_countries = {
    "Australia": "AU",
    "Austria": "AT",
    "Belgium": "BE",
    "Bulgaria": "BG",
    "Canada": "CA",
    "Croatia": "HR",
    "Czech Republic": "CZ",
    "Denmark": "DK",
    "Estonia": "EE",
    "Finland": "FI",
    "France": "FR",
    "Germany": "DE",
    "Greece": "GR",
    "Hungary": "HU",
    "Iceland": "IS",
    "Ireland": "IE",
    "Italy": "IT",
    "Japan": "JP",
    "Latvia": "LV",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Malta": "MT",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Norway": "NO",
    "Poland": "PL",
    "Portugal": "PT",
    "Republic of Cyprus": "CY",
    "Romania": "RO",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "South Korea": "KR",
    "Spain": "ES",
    "Sweden": "SE",
    "Switzerland": "CH",
    "UK": "GB",
    "USA": "US",
}


def get_airport_codes(
    country_code: str, airport_type: str = LARGE_AIRPORT, page_size: int = PAGE_SIZE
) -> List:
    col_string = "%2C".join(COLUMNS)
    API_URL = f"https://airportcodes.io/en/wp-json/aym/v1/table_data/airport/?columns={col_string}&take={PAGE_SIZE}&skip=0&type={airport_type}&country={country_code}"
    response_ = requests.get(API_URL, headers=headers)
    response = json.loads(response_.text)
    if response["status"] == "success":
        return [_dict["airport.iata"] for _dict in response["results"]]
    return []

cached_list = [
    "ADL",
    "BNE",
    "CBR",
    "MEL",
    "PER",
    "SYD",
    "VIE",
    "BRU",
    "CRL",
    "LGG",
    "BOJ",
    "SOF",
    "VAR",
    "YYC",
    "YEG",
    "YHZ",
    "YYZ",
    "YUL",
    "YOW",
    "YYT",
    "YVR",
    "YYJ",
    "YWG",
    "ZAG",
    "PRG",
    "AAL",
    "BLL",
    "CPH",
    "TLL",
    "HEL",
    "BOD",
    "CDG",
    "BSL",
    "LYS",
    "MRS",
    "NCE",
    "ORY",
    "TLS",
    "SXF",
    "TXL",
    "BRE",
    "CGN",
    "DTM",
    "DRS",
    "DUS",
    "BER",
    "FRA",
    "HAM",
    "HAJ",
    "FKB",
    "LEJ",
    "MUC",
    "FMO",
    "NUE",
    "RMS",
    "STR",
    "ATH",
    "HER",
    "SKG",
    "BUD",
    "KEF",
    "ORK",
    "DUB",
    "SNN",
    "BRI",
    "BLQ",
    "CAG",
    "CTA",
    "CIA",
    "PMO",
    "GOA",
    "BGY",
    "FCO",
    "MXP",
    "LIN",
    "NAP",
    "PSA",
    "TSF",
    "TRN",
    "VCE",
    "VRN",
    "NGO",
    "FUK",
    "DNA",
    "KOJ",
    "KIX",
    "FSZ",
    "OKA",
    "NRT",
    "CTS",
    "ITM",
    "HND",
    "OKO",
    "RIX",
    "VNO",
    "LUX",
    "MLA",
    "AMS",
    "EIN",
    "AKL",
    "CHC",
    "WLG",
    "BGO",
    "BOO",
    "OSL",
    "SVG",
    "TOS",
    "TRD",
    "WRO",
    "GDN",
    "KTW",
    "KRK",
    "WMI",
    "POZ",
    "WAW",
    "FAO",
    "OPO",
    "LIS",
    "PDL",
    "TER",
    "LCA",
    "PFO",
    "OTP",
    "SIN",
    "BTS",
    "LJU",
    "PUS",
    "GMP",
    "ICN",
    "CJU",
    "KUV",
    "MWX",
    "OSN",
    "MAD",
    "ALC",
    "BCN",
    "LPA",
    "SPC",
    "AGP",
    "PMI",
    "SCQ",
    "TFN",
    "TFS",
    "GOT",
    "LLA",
    "MMX",
    "ARN",
    "GVA",
    "ZRH",
    "ABZ",
    "BFS",
    "BHX",
    "BOH",
    "BRS",
    "CWL",
    "EMA",
    "EDI",
    "EXT",
    "BHD",
    "GLA",
    "LBA",
    "LPL",
    "LGW",
    "LHR",
    "LTN",
    "STN",
    "MAN",
    "NCL",
    "NWI",
    "AKT",
    "BZZ",
    "FFD",
    "LKZ",
    "MHZ",
    "DSA",
    "SOU",
    "SPI",
    "ABQ",
    "LTS",
    "AVL",
    "AGS",
    "AUS",
    "GRB",
    "BWI",
    "BGR",
    "BAD",
    "BAB",
    "LIT",
    "BIL",
    "BHM",
    "LEX",
    "BFI",
    "BOI",
    "BDL",
    "BUF",
    "CVS",
    "BMI",
    "CHS",
    "CLT",
    "MDW",
    "ORD",
    "RFD",
    "CVG",
    "COS",
    "CLE",
    "CAE",
    "CBM",
    "CRP",
    "DFW",
    "DAL",
    "MSN",
    "HNL",
    "DAB",
    "DEN",
    "DSM",
    "VPS",
    "DTW",
    "DLF",
    "MGE",
    "DOV",
    "DBQ",
    "DLH",
    "DYS",
    "EDW",
    "OMA",
    "ERI",
    "FAI",
    "SKA",
    "FLL",
    "FSM",
    "FWA",
    "AFW",
    "FTW",
    "BOS",
    "MKE",
    "PIA",
    "IAH",
    "ROC",
    "GSP",
    "GUS",
    "GPT",
    "ATL",
    "HMN",
    "HSV",
    "IND",
    "JAN",
    "JAX",
    "DAY",
    "JFK",
    "CMH",
    "SNA",
    "ADW",
    "JLN",
    "MCI",
    "LGA",
    "LFT",
    "LFI",
    "LAX",
    "MSY",
    "SDF",
    "CHA",
    "LBB",
    "LUF",
    "MCF",
    "MHT",
    "MBS",
    "LAS",
    "TCM",
    "TYS",
    "MEM",
    "OAK",
    "MIA",
    "MSP",
    "MOB",
    "MLU",
    "MGM",
    "MUO",
    "BNA",
    "EWR",
    "PHF",
    "ORF",
    "SJC",
    "ONT",
    "MCO",
    "SFB",
    "PBI",
    "PHL",
    "PHX",
    "GSO",
    "PIT",
    "PDX",
    "PWM",
    "MLI",
    "RDU",
    "RND",
    "HIB",
    "RNO",
    "RIC",
    "AMA",
    "LCK",
    "ROA",
    "WRB",
    "RST",
    "DCA",
    "SMF",
    "SLC",
    "SAT",
    "SAN",
    "SFO",
    "SRQ",
    "SAV",
    "BLV",
    "SEA",
    "GSB",
    "SSC",
    "SPS",
    "SUX",
    "SBN",
    "RSW",
    "SUS",
    "GEG",
    "SGF",
    "STL",
    "SYR",
    "TLH",
    "TPA",
    "ANC",
    "CID",
    "PVD",
    "TIK",
    "TOL",
    "SUU",
    "TRI",
    "HTS",
    "TUS",
    "TUL",
    "PAM",
    "END",
    "VBG",
    "IAD",
    "SZL",
    "ICT",
    "OKC",
    "HOU",
    "FFO",
    "CRW",
    "IBZ"
]
cached_dict = {
    "AU": ["ADL", "BNE", "CBR", "MEL", "PER", "SYD"],
    "AT": ["VIE"],
    "BE": ["BRU", "CRL", "LGG"],
    "BG": ["BOJ", "SOF", "VAR"],
    "CA": ["YYC", "YEG", "YHZ", "YYZ", "YUL", "YOW", "YYT", "YVR", "YYJ", "YWG"],
    "HR": ["ZAG"],
    "CZ": ["PRG"],
    "DK": ["AAL", "BLL", "CPH"],
    "EE": ["TLL"],
    "FI": ["HEL"],
    "FR": ["BOD", "CDG", "BSL", "LYS", "MRS", "NCE", "ORY", "TLS"],
    "DE": [
        "SXF",
        "TXL",
        "BRE",
        "CGN",
        "DTM",
        "DRS",
        "DUS",
        "FRA",
        "HAM",
        "HAJ",
        "FKB",
        "LEJ",
        "MUC",
        "FMO",
        "NUE",
        "RMS",
        "STR",
        "BER"
    ],
    "GR": ["ATH", "HER", "SKG"],
    "HU": ["BUD"],
    "IS": ["KEF"],
    "IE": ["ORK", "DUB", "SNN"],
    "IT": [
        "BRI",
        "BLQ",
        "CAG",
        "CTA",
        "CIA",
        "PMO",
        "GOA",
        "BGY",
        "FCO",
        "MXP",
        "LIN",
        "NAP",
        "PSA",
        "TSF",
        "TRN",
        "VCE",
        "VRN",
    ],
    "JP": [
        "NGO",
        "FUK",
        "DNA",
        "KOJ",
        "KIX",
        "FSZ",
        "OKA",
        "NRT",
        "CTS",
        "ITM",
        "HND",
        "OKO",
    ],
    "LV": ["RIX"],
    "LI": [],
    "LT": ["VNO"],
    "LU": ["LUX"],
    "MT": ["MLA"],
    "NL": ["AMS", "EIN"],
    "NZ": ["AKL", "CHC", "WLG"],
    "NO": ["BGO", "BOO", "OSL", "SVG", "TOS", "TRD"],
    "PL": ["WRO", "GDN", "KTW", "KRK", "WMI", "POZ", "WAW"],
    "PT": ["FAO", "OPO", "LIS", "PDL", "TER"],
    "CY": ["LCA", "PFO"],
    "RO": ["OTP"],
    "SG": ["SIN"],
    "SK": ["BTS"],
    "SI": ["LJU"],
    "KR": ["PUS", "GMP", "ICN", "CJU", "KUV", "MWX", "OSN"],
    "ES": ["MAD", "ALC", "BCN", "LPA", "SPC", "AGP", "PMI", "SCQ", "TFN", "TFS", "IBZ"],
    "SE": ["GOT", "LLA", "MMX", "ARN"],
    "CH": ["GVA", "ZRH"],
    "GB": [
        "ABZ",
        "BFS",
        "BHX",
        "BOH",
        "BRS",
        "CWL",
        "EMA",
        "EDI",
        "EXT",
        "BHD",
        "GLA",
        "LBA",
        "LPL",
        "LGW",
        "LHR",
        "LTN",
        "STN",
        "MAN",
        "NCL",
        "NWI",
        "AKT",
        "BZZ",
        "FFD",
        "LKZ",
        "MHZ",
        "DSA",
        "SOU",
    ],
    "US": [
        "SPI",
        "ABQ",
        "LTS",
        "AVL",
        "AGS",
        "AUS",
        "GRB",
        "BWI",
        "BGR",
        "BAD",
        "BAB",
        "LIT",
        "BIL",
        "BHM",
        "LEX",
        "BFI",
        "BOI",
        "BDL",
        "BUF",
        "CVS",
        "BMI",
        "CHS",
        "CLT",
        "MDW",
        "ORD",
        "RFD",
        "CVG",
        "COS",
        "CLE",
        "CAE",
        "CBM",
        "CRP",
        "DFW",
        "DAL",
        "MSN",
        "HNL",
        "DAB",
        "DEN",
        "DSM",
        "VPS",
        "DTW",
        "DLF",
        "MGE",
        "DOV",
        "DBQ",
        "DLH",
        "DYS",
        "EDW",
        "OMA",
        "ERI",
        "FAI",
        "SKA",
        "FLL",
        "FSM",
        "FWA",
        "AFW",
        "FTW",
        "BOS",
        "MKE",
        "PIA",
        "IAH",
        "ROC",
        "GSP",
        "GUS",
        "GPT",
        "ATL",
        "HMN",
        "HSV",
        "IND",
        "JAN",
        "JAX",
        "DAY",
        "JFK",
        "CMH",
        "SNA",
        "ADW",
        "JLN",
        "MCI",
        "LGA",
        "LFT",
        "LFI",
        "LAX",
        "MSY",
        "SDF",
        "CHA",
        "LBB",
        "LUF",
        "MCF",
        "MHT",
        "MBS",
        "LAS",
        "TCM",
        "TYS",
        "MEM",
        "OAK",
        "MIA",
        "MSP",
        "MOB",
        "MLU",
        "MGM",
        "MUO",
        "BNA",
        "EWR",
        "PHF",
        "ORF",
        "SJC",
        "ONT",
        "MCO",
        "SFB",
        "PBI",
        "PHL",
        "PHX",
        "GSO",
        "PIT",
        "PDX",
        "PWM",
        "MLI",
        "RDU",
        "RND",
        "HIB",
        "RNO",
        "RIC",
        "AMA",
        "LCK",
        "ROA",
        "WRB",
        "RST",
        "DCA",
        "SMF",
        "SLC",
        "SAT",
        "SAN",
        "SFO",
        "SRQ",
        "SAV",
        "BLV",
        "SEA",
        "GSB",
        "SSC",
        "SPS",
        "SUX",
        "SBN",
        "RSW",
        "SUS",
        "GEG",
        "SGF",
        "STL",
        "SYR",
        "TLH",
        "TPA",
        "ANC",
        "CID",
        "PVD",
        "TIK",
        "TOL",
        "SUU",
        "TRI",
        "HTS",
        "TUS",
        "TUL",
        "PAM",
        "END",
        "VBG",
        "IAD",
        "SZL",
        "ICT",
        "OKC",
        "HOU",
        "FFO",
        "CRW",
    ],
}

if __name__ == "__main__":
    # eligible_airports = {}
    # all_airports = []
    # for country_code in eligible_countries.values():
    #     airport_codes = get_airport_codes(country_code)
    #     eligible_airports[country_code] = airport_codes
    #     all_airports.extend(airport_codes)

    print(cached_dict)
    print(cached_list)
